excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://ndjones.github.io
title: Nick Jones
tagline: Research is going digital
description: Thoughts on changes to research practice, policy, and platforms
paginate: 5
